fedscgen:
  workflow: "train" # train or correction
  data:
    adata: raw.h5ad
    batch_key: batch
    cell_key: cell_type
  smpc: True # True or False
  n_rounds: 2 # number of federated rounds
  model:
    init_model: None
    ref_model: model.pth
    hidden_layer_sizes: "800,800"
    z_dimension: 10
  train:
    lr: 0.01
    n_epochs: 3
    batch_size: 32